# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /mnt/Biblioteca/Motores/Unreal Engine

TARGETS = \
	ChaosTestHarness \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	UnrealS7-Android-DebugGame  \
	UnrealS7-Android-Development  \
	UnrealS7-Android-Shipping  \
	UnrealS7-Linux-DebugGame  \
	UnrealS7-Linux-Development  \
	UnrealS7-Linux-Shipping  \
	UnrealS7-LinuxArm64-DebugGame  \
	UnrealS7-LinuxArm64-Development  \
	UnrealS7-LinuxArm64-Shipping  \
	UnrealS7 \
	UnrealS7Editor-Linux-DebugGame  \
	UnrealS7Editor-Linux-Development  \
	UnrealS7Editor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend UnrealS7Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UnrealS7Editor-Linux-Debug


ChaosTestHarness: ChaosTestHarness-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

UnrealS7-Android-DebugGame:
	 $(BUILD) UnrealS7 Android DebugGame  -Project="/mnt/Biblioteca/Proyectos/Unreal/UnrealS7/UnrealS7.uproject" $(ARGS)

UnrealS7-Android-Development:
	 $(BUILD) UnrealS7 Android Development  -Project="/mnt/Biblioteca/Proyectos/Unreal/UnrealS7/UnrealS7.uproject" $(ARGS)

UnrealS7-Android-Shipping:
	 $(BUILD) UnrealS7 Android Shipping  -Project="/mnt/Biblioteca/Proyectos/Unreal/UnrealS7/UnrealS7.uproject" $(ARGS)

UnrealS7-Linux-DebugGame:
	 $(BUILD) UnrealS7 Linux DebugGame  -Project="/mnt/Biblioteca/Proyectos/Unreal/UnrealS7/UnrealS7.uproject" $(ARGS)

UnrealS7-Linux-Development:
	 $(BUILD) UnrealS7 Linux Development  -Project="/mnt/Biblioteca/Proyectos/Unreal/UnrealS7/UnrealS7.uproject" $(ARGS)

UnrealS7-Linux-Shipping:
	 $(BUILD) UnrealS7 Linux Shipping  -Project="/mnt/Biblioteca/Proyectos/Unreal/UnrealS7/UnrealS7.uproject" $(ARGS)

UnrealS7-LinuxArm64-DebugGame:
	 $(BUILD) UnrealS7 LinuxArm64 DebugGame  -Project="/mnt/Biblioteca/Proyectos/Unreal/UnrealS7/UnrealS7.uproject" $(ARGS)

UnrealS7-LinuxArm64-Development:
	 $(BUILD) UnrealS7 LinuxArm64 Development  -Project="/mnt/Biblioteca/Proyectos/Unreal/UnrealS7/UnrealS7.uproject" $(ARGS)

UnrealS7-LinuxArm64-Shipping:
	 $(BUILD) UnrealS7 LinuxArm64 Shipping  -Project="/mnt/Biblioteca/Proyectos/Unreal/UnrealS7/UnrealS7.uproject" $(ARGS)

UnrealS7: UnrealS7-Linux-Development

UnrealS7Editor-Linux-DebugGame:
	 $(BUILD) UnrealS7Editor Linux DebugGame  -Project="/mnt/Biblioteca/Proyectos/Unreal/UnrealS7/UnrealS7.uproject" $(ARGS)

UnrealS7Editor-Linux-Development:
	 $(BUILD) UnrealS7Editor Linux Development  -Project="/mnt/Biblioteca/Proyectos/Unreal/UnrealS7/UnrealS7.uproject" $(ARGS)

UnrealS7Editor: UnrealS7Editor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/mnt/Biblioteca/Proyectos/Unreal/UnrealS7/UnrealS7.uproject" -Game 

.PHONY: $(TARGETS)
